File.read!("input")
|> String.split("\n")
|> Enum.map(fn s ->  String.split(s) |> Enum.map(&String.to_integer/1) |> List.to_tuple() end)
|> Enum.unzip()
|> Tuple.to_list()
|> Enum.map(&Enum.sort/1)
|> Enum.zip()
|> Enum.map(fn {e1, e2} -> abs(e1 - e2)  end )
|> Enum.sum()
|> IO.inspect(label: :out)
